sudo: required
services: 
  -docker
env:
  global: 
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_45ee027500ef_key -iv $encrypted_45ee027500ef_iv -in multi-k8s-340921-4bdf62a0e744.json.enc -out multi-k8s-340921-4bdf62a0e744.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-340921-4bdf62a0e744.json
  - gcloud config set project multi-k8s-340921
  - gcloud config set compute/zone europe-west1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sythnlkn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sythnlkn/react-test npm test

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: master


