apiVersion: apps/v1
kind: Deployment
metadata :
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata: 
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: cygnetops/multi-client-k8s
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: "/health-check"
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            